server:
  port: 80
  servlet:
    session:
      timeout: 30m #session会话超时时间，默认情况下30分钟，不能小于1分钟
      cookie:
        name: MY_JSESSIONID # 指定浏览器cookie中保存的SessionId的名字


spring:
  session:
    store-type: none # session存储方式可选用redis
  thymeleaf:
    cache: false
  #数据源配置
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:23306/employment?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接个数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位为毫秒
      max-wait: 5000
      # 状态监控
      filter:
        stat:
          # 使能状态监控
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # 监控过滤器
      web-stat-filter:
        enabled: true
        # 配置过滤器不拦截哪些uri
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      # druid 监控页面
      stat-view-servlet:
        enabled: true
        # 配置监控界面uri
        url-pattern: /druid/*
        reset-enable: false
        # 配置登陆用户名
        login-username: root
        # 配置登陆密码
        login-password: root

  mvc:
    hiddenmethod:
      filter:
        enabled: true #springBoot 2.2版本后要手动开启对delete、put方法的处理
    date-format: yyyy-MM-dd # 处理前端给过来的data格式

  mail:
    username: 2239109628@qq.com
    password: qudsvkdumsoadhjd
    host: smtp.qq.com
    properties:
      smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB


mybatis-plus:
  # 指定实体类所有包
  type-aliases-package: com.breez.web.entities

#日志级别，会打印sql语句
logging:
  level:
    com.breez.web.mapper: debug
    com.breez.web.service.JavaMailService: debug




mengxuegu:
  security:
    authentication:
      loginPage: /login/page # 响应认证（登录）页面的url
      loginProcessingUrl: /login/form # 登录表单提交处理的url
      usernameParameter: name # 登录表单提交的用户名的属性名
      passwordParameter: pwd # 登录表单提交的密码的属性名
      staticPath: # 静态资源
        - /dist/**
        - /modules/**
        - /plugins/**
        - /assets/**
        - /ow/**
        - /position/apply # 放行职位查找界面
        - /position/customPage # 放行职位信息获取界面
        - /position/apply/info/** # 放行职位详情界面
        - /webjars/** #放行webjars
        - /user/register
        - /user/sendCode
        - /user/forget
      loginType: REDIRECT #认证之后响应的类型:JSON/REDIRECT

      # "/code/image", "/mobile/page", "/code/mobile"
      imageCodeUrl: /code/image # 获取图形验证码地址
      mobileCodeUrl: /code/mobile # 发送手机验证码地址
      mobilePage: /mobile/page # 前往手机登录页面
      tokenValiditySeconds: 604800 # 记住我功能有效时长


